### ISSUE TITLE
Problematic sampling rate of LFPs

### ISSUE THREAD

**Issue by mpompolas** [tdtneuro/TDTMatlabSDK#1]
The  TDT importer that is currently on your website gives problematic sampling rate on the LFP streams.

Example command:
data = TDTbin2mat(DataFolder, 'T1', 0, 'T2', 1); % 1 second segment
![aa](https://user-images.githubusercontent.com/23224563/73786111-a34a1900-4766-11ea-9fae-ecc26cea3f9f.png)

 

The sampling rate should be: 2034.5052Hz as is printed on the command line:
 
![aa](https://user-images.githubusercontent.com/23224563/73786145-b3fa8f00-4766-11ea-84e8-9480c8051013.png)

**Comment by tdtneuro** [comment]
Fixed in 8ba3d45b263cc0f7a98daaf78880cbc8d0ce8821
